# 画面をマウスで操作（ペイン選択・スクロールなど）
#set -g mouse on
set -g mouse off 

# コピーモードをviスタイルに（上下k/j、選択vなど）
setw -g mode-keys vi

# セッション開始時のデフォルトシェル
set-option -g default-shell /bin/zsh

# tmux設定ファイルの再読み込み
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# ステータスバーの色
set-option -g status-bg colour235
set-option -g status-fg white
set-option -g status-left '#[fg=green]#H'
set-option -g status-right '#[fg=cyan]%Y-%m-%d %H:%M'

# 履歴スクロール数
set-option -g history-limit 10000
